### PR TITLE
Fixes #1: Rewrite tests & run with gulp

### LINKED ISSUE #1: Rewrite tests & run with gulp

### PR DESCRIPTION
**Pull request by lmorchard**
Very simple test to match the simple module: It does a small hack to swap out the real firefox-client for a mock class and tests that `connect()` was called. Test works on Mac, Linux, and Windows

### CODE REVIEW

**Comment by tofumatt** [comment]
Most of the removed tests look to belong in other modules, not sure if we need note any yet-to-implement before removing them.

If not: r+, though if we are gonna need to mock more objects maybe we should look into a standard mocking library.

**Comment by lmorchard** [comment]
Oh yeah, actually I'll take a look at [mfncooper/mockery](https://github.com/mfncooper/mockery) tomorrow. Should have done that to begin with, rather than copypasta'ing ancient mock hacks I had lying around :)

**Comment by tofumatt** [comment]
Cool, in that case let's wait on this 'til the mock is merged in?

**Comment by lmorchard** [comment]
There we go: switched to mockery, and it seemed easy enough & cleaner

**Comment by tofumatt** [comment]
Whoa, sooooo much nicer :+1:

**Pull request merged**
